[package]
name = "codegame"
version = "0.3.0"
authors = ["kuviman <kuviman@gmail.com>"]
description = "CodeGame framework"
license = "MIT"
homepage = "https://github.com/codeforces/codegame"
edition = "2018"

[features]
default = ["rendering"]
rendering = ["geng"]

[dependencies]
batbox = "0.3"
geng = { version = "0.3", optional = true }
serde_json = "1"
serde = "1"

[target.'cfg(any(target_arch = "asmjs", target_arch = "wasm32"))'.dependencies]
stdweb = "0.4.9"