[package]
name = "codegame"
version = "0.1.0"
authors = ["kuviman <kuviman@gmail.com>"]
edition = "2018"

[features]
default = ["rendering"]
rendering = ["geng"]

[dependencies]
batbox = { git = "https://github.com/kuviman/batbox" }
geng = { git = "https://github.com/kuviman/geng", optional = true }
serde_json = "1"
serde = "1"

[target.'cfg(any(target_arch = "asmjs", target_arch = "wasm32"))'.dependencies]
stdweb = "0.4.9"